    const productsData = {
        'Accesorios y Regaleria': [
            { imagen: 'vit1.jpg', descripcion: 'Colágeno' },
            { imagen: 'vit2.jpg', descripcion: 'Megacistin max' },
            { imagen: 'vit3.jpg', descripcion: 'Cabello, piel y uñas' },
            { imagen: 'vit4.jpg', descripcion: 'Omegan' },
        ],
        'Relax': [
            { imagen: 'vit1.jpg', descripcion: 'Colágeno' },
            { imagen: 'vit2.jpg', descripcion: 'Megacistin max' },
            { imagen: 'vit3.jpg', descripcion: 'Cabello, piel y uñas' },
            { imagen: 'vit4.jpg', descripcion: 'Omegan' },
        ],
        'Electro medicina': [
            { imagen: 'cuidado1.jpg', descripcion: 'Esponja vegetal' },
            { imagen: 'cuidado2.jpg', descripcion: 'Cepillo de dientes colgate triple acción' },
            { imagen: 'cuidado3.jpg', descripcion: 'Pasta de dientes SriSri sudanta' }
        ],
        'Fitness & Movimiento': [
            { imagen: 'fit1.jpg', descripcion: '' },
            { imagen: 'fit2.jpg', descripcion: '' },
            { imagen: 'fit3.jpg', descripcion: '' },
            { imagen: 'fit4.jpg', descripcion: '' },
            { imagen: 'fit5.jpg', descripcion: '' },
            { imagen: 'fit6.jpg', descripcion: '' },
            { imagen: 'fit7.jpg', descripcion: '' },
            { imagen: 'fit8.jpg', descripcion: '' },
            { imagen: 'fit9.jpg', descripcion: '' },
            { imagen: 'fit10.jpg', descripcion: '' },
            { imagen: 'fit11.jpg', descripcion: '' },
            { imagen: 'fit12.jpg', descripcion: '' },
            { imagen: 'fit13.jpg', descripcion: '' },
            { imagen: 'fit14.jpg', descripcion: '' },
            { imagen: 'fit15.jpg', descripcion: '' },
            { imagen: 'fit16.jpg', descripcion: '' },
            { imagen: 'fit17.jpg', descripcion: '' },
            { imagen: 'fit18.jpg', descripcion: '' },
            { imagen: 'fit19.jpg', descripcion: '' },
            { imagen: 'fit20.jpg', descripcion: '' },
            { imagen: 'fit21.jpg', descripcion: '' },
            { imagen: 'fit22.jpg', descripcion: '' },
            { imagen: 'fit23.jpg', descripcion: '' },
            { imagen: 'fit24.jpg', descripcion: '' },
            { imagen: 'fit25.jpg', descripcion: '' },
            { imagen: 'fit26.jpg', descripcion: '' },
            { imagen: 'fit27.jpg', descripcion: '' },
            { imagen: 'fit28.jpg', descripcion: '' },
            { imagen: 'fit29.jpg', descripcion: '' },
            { imagen: 'fit30.jpg', descripcion: '' },
            { imagen: 'fit31.jpg', descripcion: '' },
            { imagen: 'fit32.jpg', descripcion: '' },
            { imagen: 'fit33.jpg', descripcion: '' },
            { imagen: 'fit35.jpg', descripcion: '' },
            { imagen: 'fit36.jpg', descripcion: '' },
            { imagen: 'fit37.jpg', descripcion: '' },
            { imagen: 'fit38.jpg', descripcion: '' },
            { imagen: 'fit39.jpg', descripcion: '' }
        ],
        'Higiene y cuidado personal': [
            { imagen: 'hcp1.jpg', descripcion: 'Carefree todos los días' },
            { imagen: 'hcp2.jpg', descripcion: 'Carefree todos los días tanga' },
            { imagen: 'hcp3.jpg', descripcion: 'Carefree protección largos' },
            { imagen: 'hcp4.jpg', descripcion: 'Carefree protección' },
            { imagen: 'hcp5.jpg', descripcion: 'Siempre Libre normal suave ' },
            { imagen: 'hcp6.jpg', descripcion: 'Siempre Libre adapt plus ultrafina suave' },
            { imagen: 'hcp7.jpg', descripcion: 'Doncella normal' },
            { imagen: 'hcp8.jpg', descripcion: 'Doncella protectores diarios' },
            { imagen: 'hcp9.jpg', descripcion: 'Nosotras clásica' },
            { imagen: 'hcp10.jpg', descripcion: 'Viasek Toallitas húmedas intimas femeninas' },
            { imagen: 'hcp11.jpg', descripcion: 'EVACOPA talle 3' },
            { imagen: 'hcp12.jpg', descripcion: 'EVACOPA talle 2' },
            { imagen: 'hcp13.jpg', descripcion: 'EVACOPA talle 1' },
            { imagen: 'hcp14.jpg', descripcion: 'o.b. mini' },
            { imagen: 'hcp15.jpg', descripcion: 'o.b. medio' },
            { imagen: 'hcp16.jpg', descripcion: 'o.b. super' },
            { imagen: 'hcp17.jpg', descripcion: 'CUTEX quitaesmalte fortalecedor' },
            { imagen: 'hcp18.jpg', descripcion: 'CUTEX quitaesmalte hipoalergénico' },
            { imagen: 'hcp19.jpg', descripcion: 'Veet kit de depilación facial' }

        ],
        'Suplementos, Vitaminas y Productos naturales': [
            { imagen: 'vit1.jpg', descripcion: 'Colágeno' },
            { imagen: 'vit2.jpg', descripcion: 'Megacistin max' },
            { imagen: 'vit3.jpg', descripcion: 'Cabello, piel y uñas' },
            { imagen: 'vit4.jpg', descripcion: 'Omegan' },
            { imagen: 'vit5.jpg', descripcion: 'Lecitina 1200' },
            { imagen: 'vit6.jpg', descripcion: 'Isoflavonas de soja' },
            { imagen: 'vit7.jpg', descripcion: 'Ginkgo 80' },
            { imagen: 'vit8.jpg', descripcion: 'Chía. Omega 3' },
            { imagen: 'vit9.jpg', descripcion: 'Guaraná, con polen y vitamina E' },
            { imagen: 'vit10.jpg', descripcion: 'Cúrcuma + jengible. Vitaminas C y E' },
            { imagen: 'vit11.jpg', descripcion: 'Clorofila' },
            { imagen: 'vit12.jpg', descripcion: 'Vitamina B12' },
            { imagen: 'vit13.jpg', descripcion: 'Vitamina C' },
            { imagen: 'vit14.jpg', descripcion: 'Nutri 100. Vitamina E' },
            { imagen: 'vit15.jpg', descripcion: 'Vitamina D' },
            { imagen: 'vit16.jpg', descripcion: 'Vitamina D3' },
            { imagen: 'vit17.jpg', descripcion: 'Curflex plus' },
            { imagen: 'vit18.jpg', descripcion: 'Curflex triple acción' },
            { imagen: 'vit19.jpg', descripcion: 'MSM artro' },
            { imagen: 'vit20.jpg', descripcion: 'Valeriana' },
            { imagen: 'vit21.jpg', descripcion: 'Serenil' },
            { imagen: 'vit22.jpg', descripcion: 'Fosfovita' },
            { imagen: 'vit23.jpg', descripcion: 'Fosfovita silver' },
            { imagen: 'vit24.jpg', descripcion: '102 mujer' },
            { imagen: 'vit25.jpg', descripcion: '102 plus' },
            { imagen: 'vit26.jpg', descripcion: 'Centrum mujer' },
            { imagen: 'vit27.jpg', descripcion: 'Centrum hombre' },
            { imagen: 'vit28.jpg', descripcion: 'Centrum silver' },
            { imagen: 'vit29.jpg', descripcion: 'Centrum base' },
            { imagen: 'vit30.jpg', descripcion: 'Redoxon. Vitamina C' },
            { imagen: 'vit31.jpg', descripcion: 'Redoxon triple acción. Vitamina D y zinc' },
            { imagen: 'vit32.jpg', descripcion: 'Redoxitos Plus. Vitamina D, vitamina C y zinc' },
            { imagen: 'vit33.jpg', descripcion: 'Supradyn forte' },
            { imagen: 'vit34.jpg', descripcion: 'Berocca Plus' },
            { imagen: 'vit35.jpg', descripcion: 'Magnesio sport' },
            { imagen: 'vit36.jpg', descripcion: 'Magnesio. Potasio y vitamina B6' },
            { imagen: 'vit37.jpg', descripcion: 'Citrato de magnesio. Vitamina D' },
            { imagen: 'vit38.jpg', descripcion: 'Quelat. Zinc, magnesio y selenio' },
            { imagen: 'vit39.jpg', descripcion: 'Spirulina siluett. Garcinia y café verde' },
            { imagen: 'sup.jpg', descripcion: '' },
            { imagen: 'sup2.jpg', descripcion: '' },
            { imagen: 'sup3.jpg', descripcion: '' },
            { imagen: 'sup4.jpg', descripcion: '' },
            { imagen: 'sup5.jpg', descripcion: '' },
            { imagen: 'sup6.jpg', descripcion: '' },
            { imagen: 'sup7.jpg', descripcion: '' },
            { imagen: 'sup8.jpg', descripcion: '' },
            { imagen: 'sup9.jpg', descripcion: '' },
            { imagen: 'sup10.jpg', descripcion: '' },
            { imagen: 'sup11.jpg', descripcion: '' },
            { imagen: 'sup12.jpg', descripcion: '' },
            { imagen: 'sup13.jpg', descripcion: '' },
            { imagen: 'sup14.jpg', descripcion: '' },
            { imagen: 'sup15.jpg', descripcion: '' },
            { imagen: 'sup16.jpg', descripcion: '' },
            { imagen: 'sup17.jpg', descripcion: '' },
            { imagen: 'sup18.jpg', descripcion: '' },
            { imagen: 'sup19.jpg', descripcion: '' },
            { imagen: 'sup20.jpg', descripcion: '' },
            { imagen: 'sup21.jpg', descripcion: '' },
            { imagen: 'sup22.jpg', descripcion: '' },
            { imagen: 'sup23.jpg', descripcion: '' },
            { imagen: 'sup24.jpg', descripcion: '' },
            { imagen: 'sup25.jpg', descripcion: '' }

        ],
    };